####
# ATENTION:
# Replace all occurences of template with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:

  # MySQL Data
  template-mysql-data:
    driver: local

services:

  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: template-mysql
    volumes:
      - template-mysql-data:/var/lib/mysql
      - ../dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=template
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.3-nginx
    container_name: template-app
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8080"
    links:
      - mysql